experiment:
  input_path: "data/input_code"      # Can be a specific .py file or a folder

llm:
  temperature: 0.0

agent:
  verbose: false
  max_iterations: 5
  enforce_strict_imports: true

logging:
  verbose: false